# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pezzotto/Projects/pyrbfnetwork

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pezzotto/Projects/pyrbfnetwork

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pezzotto/Projects/pyrbfnetwork/CMakeFiles /home/pezzotto/Projects/pyrbfnetwork/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pezzotto/Projects/pyrbfnetwork/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pyrbfnet

# Build rule for target.
pyrbfnet: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pyrbfnet
.PHONY : pyrbfnet

# fast build rule for target.
pyrbfnet/fast:
	$(MAKE) -f CMakeFiles/pyrbfnet.dir/build.make CMakeFiles/pyrbfnet.dir/build
.PHONY : pyrbfnet/fast

#=============================================================================
# Target rules for targets named rbfnetwork

# Build rule for target.
rbfnetwork: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rbfnetwork
.PHONY : rbfnetwork

# fast build rule for target.
rbfnetwork/fast:
	$(MAKE) -f CMakeFiles/rbfnetwork.dir/build.make CMakeFiles/rbfnetwork.dir/build
.PHONY : rbfnetwork/fast

rbfn_bindings.o: rbfn_bindings.cpp.o
.PHONY : rbfn_bindings.o

# target to build an object file
rbfn_bindings.cpp.o:
	$(MAKE) -f CMakeFiles/pyrbfnet.dir/build.make CMakeFiles/pyrbfnet.dir/rbfn_bindings.cpp.o
.PHONY : rbfn_bindings.cpp.o

rbfn_bindings.i: rbfn_bindings.cpp.i
.PHONY : rbfn_bindings.i

# target to preprocess a source file
rbfn_bindings.cpp.i:
	$(MAKE) -f CMakeFiles/pyrbfnet.dir/build.make CMakeFiles/pyrbfnet.dir/rbfn_bindings.cpp.i
.PHONY : rbfn_bindings.cpp.i

rbfn_bindings.s: rbfn_bindings.cpp.s
.PHONY : rbfn_bindings.s

# target to generate assembly for a file
rbfn_bindings.cpp.s:
	$(MAKE) -f CMakeFiles/pyrbfnet.dir/build.make CMakeFiles/pyrbfnet.dir/rbfn_bindings.cpp.s
.PHONY : rbfn_bindings.cpp.s

rbfnetwork.o: rbfnetwork.cpp.o
.PHONY : rbfnetwork.o

# target to build an object file
rbfnetwork.cpp.o:
	$(MAKE) -f CMakeFiles/pyrbfnet.dir/build.make CMakeFiles/pyrbfnet.dir/rbfnetwork.cpp.o
	$(MAKE) -f CMakeFiles/rbfnetwork.dir/build.make CMakeFiles/rbfnetwork.dir/rbfnetwork.cpp.o
.PHONY : rbfnetwork.cpp.o

rbfnetwork.i: rbfnetwork.cpp.i
.PHONY : rbfnetwork.i

# target to preprocess a source file
rbfnetwork.cpp.i:
	$(MAKE) -f CMakeFiles/pyrbfnet.dir/build.make CMakeFiles/pyrbfnet.dir/rbfnetwork.cpp.i
	$(MAKE) -f CMakeFiles/rbfnetwork.dir/build.make CMakeFiles/rbfnetwork.dir/rbfnetwork.cpp.i
.PHONY : rbfnetwork.cpp.i

rbfnetwork.s: rbfnetwork.cpp.s
.PHONY : rbfnetwork.s

# target to generate assembly for a file
rbfnetwork.cpp.s:
	$(MAKE) -f CMakeFiles/pyrbfnet.dir/build.make CMakeFiles/pyrbfnet.dir/rbfnetwork.cpp.s
	$(MAKE) -f CMakeFiles/rbfnetwork.dir/build.make CMakeFiles/rbfnetwork.dir/rbfnetwork.cpp.s
.PHONY : rbfnetwork.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pyrbfnet"
	@echo "... rbfnetwork"
	@echo "... rebuild_cache"
	@echo "... rbfn_bindings.o"
	@echo "... rbfn_bindings.i"
	@echo "... rbfn_bindings.s"
	@echo "... rbfnetwork.o"
	@echo "... rbfnetwork.i"
	@echo "... rbfnetwork.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

